### ISSUE TITLE
Not working If Location OFF 

### ISSUE THREAD

**Issue by amiyo-biswas** [askfortricks/FusedLocationProviderClient#1]
Test case 
First run
Condition-> Location OFF
App Run. Auto location Dialog->Click OK then Runtime permission Appear. Allow Permission . After that Didn't get LATITUDE and LONGITUDE.

**Comment by raviyadav4875** [comment]
@amiyo-biswas are you testing in device or emulator?

**Comment by amiyo-biswas** [comment]
Thanks for quick response. Hand Set. Moto C plus. API LEVEL 24.

**Comment by raviyadav4875** [comment]
ok. I will test and update the thread.

**Comment by amiyo-biswas** [comment]
As same as, Test case 2

LOCATION OFF ---> App run--> Dialog for best results---->OK

**Comment by raviyadav4875** [comment]
Faced with similar issue in https://github.com/askfortricks/FusedLocationProvider-Api-Demo .  I have applied some changes in the above demo.May be something similar we need to do.
Please read the comments section from [](http://www.askfortricks.com/2016/03/get-location-android-using-fused-location-provider-api/) you will get some idea.
Getting exception in **getLastLocation()-->onComplete** method. Exception in task

**Comment by amiyo-biswas** [comment]
OK. I will.

**Comment by raviyadav4875** [comment]
@amiyo-biswas I have uploaded a fresh new code with whole new stuff which solves the issue.
